/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTesteRouteImport } from './routes/_authenticated/teste'
import { Route as AuthenticatedProjetoIntegradorRouteImport } from './routes/_authenticated/projeto-integrador'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPdiRouteImport } from './routes/_authenticated/pdi'
import { Route as AuthenticatedLiderancaIaRouteImport } from './routes/_authenticated/lideranca-ia'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChaRouteImport } from './routes/_authenticated/cha'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTesteRoute = AuthenticatedTesteRouteImport.update({
  id: '/teste',
  path: '/teste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetoIntegradorRoute =
  AuthenticatedProjetoIntegradorRouteImport.update({
    id: '/projeto-integrador',
    path: '/projeto-integrador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdiRoute = AuthenticatedPdiRouteImport.update({
  id: '/pdi',
  path: '/pdi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiderancaIaRoute =
  AuthenticatedLiderancaIaRouteImport.update({
    id: '/lideranca-ia',
    path: '/lideranca-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChaRoute = AuthenticatedChaRouteImport.update({
  id: '/cha',
  path: '/cha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/cha': typeof AuthenticatedChaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/lideranca-ia': typeof AuthenticatedLiderancaIaRoute
  '/pdi': typeof AuthenticatedPdiRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/projeto-integrador': typeof AuthenticatedProjetoIntegradorRoute
  '/teste': typeof AuthenticatedTesteRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/cha': typeof AuthenticatedChaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/lideranca-ia': typeof AuthenticatedLiderancaIaRoute
  '/pdi': typeof AuthenticatedPdiRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/projeto-integrador': typeof AuthenticatedProjetoIntegradorRoute
  '/teste': typeof AuthenticatedTesteRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/cha': typeof AuthenticatedChaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/lideranca-ia': typeof AuthenticatedLiderancaIaRoute
  '/_authenticated/pdi': typeof AuthenticatedPdiRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/projeto-integrador': typeof AuthenticatedProjetoIntegradorRoute
  '/_authenticated/teste': typeof AuthenticatedTesteRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistente'
    | '/atividades'
    | '/cha'
    | '/dashboard'
    | '/desafios'
    | '/diario'
    | '/lideranca-ia'
    | '/pdi'
    | '/perfil'
    | '/projeto-integrador'
    | '/teste'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistente'
    | '/atividades'
    | '/cha'
    | '/dashboard'
    | '/desafios'
    | '/diario'
    | '/lideranca-ia'
    | '/pdi'
    | '/perfil'
    | '/projeto-integrador'
    | '/teste'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assistente'
    | '/_authenticated/atividades'
    | '/_authenticated/cha'
    | '/_authenticated/dashboard'
    | '/_authenticated/desafios'
    | '/_authenticated/diario'
    | '/_authenticated/lideranca-ia'
    | '/_authenticated/pdi'
    | '/_authenticated/perfil'
    | '/_authenticated/projeto-integrador'
    | '/_authenticated/teste'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teste': {
      id: '/_authenticated/teste'
      path: '/teste'
      fullPath: '/teste'
      preLoaderRoute: typeof AuthenticatedTesteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projeto-integrador': {
      id: '/_authenticated/projeto-integrador'
      path: '/projeto-integrador'
      fullPath: '/projeto-integrador'
      preLoaderRoute: typeof AuthenticatedProjetoIntegradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdi': {
      id: '/_authenticated/pdi'
      path: '/pdi'
      fullPath: '/pdi'
      preLoaderRoute: typeof AuthenticatedPdiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lideranca-ia': {
      id: '/_authenticated/lideranca-ia'
      path: '/lideranca-ia'
      fullPath: '/lideranca-ia'
      preLoaderRoute: typeof AuthenticatedLiderancaIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cha': {
      id: '/_authenticated/cha'
      path: '/cha'
      fullPath: '/cha'
      preLoaderRoute: typeof AuthenticatedChaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedChaRoute: typeof AuthenticatedChaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedLiderancaIaRoute: typeof AuthenticatedLiderancaIaRoute
  AuthenticatedPdiRoute: typeof AuthenticatedPdiRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProjetoIntegradorRoute: typeof AuthenticatedProjetoIntegradorRoute
  AuthenticatedTesteRoute: typeof AuthenticatedTesteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedChaRoute: AuthenticatedChaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedLiderancaIaRoute: AuthenticatedLiderancaIaRoute,
  AuthenticatedPdiRoute: AuthenticatedPdiRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProjetoIntegradorRoute: AuthenticatedProjetoIntegradorRoute,
  AuthenticatedTesteRoute: AuthenticatedTesteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
